=== rengal/template.net/Resto.Front.PrintTemplates/TemplateModels.xsd
<?xml version="1.0" encoding="utf-8"?>
<schema
    targetNamespace="http://iiko.ru/XmlSchemas/TemplateModels.xsd"
    xmlns:x="http://iiko.ru/XmlSchemas/TemplateModels.xsd"
    xmlns="http://www.w3.org/2001/XMLSchema"
    elementFormDefault="qualified">

    <simpleType name="StandardType">
        <restriction base="string">
            <enumeration value="Guid" />
            <enumeration value="Guid?" />
            <enumeration value="bool" />
            <enumeration value="bool?" />
            <enumeration value="decimal" />
            <enumeration value="decimal?" />
            <enumeration value="string" />
            <enumeration value="int" />
            <enumeration value="int?" />
            <enumeration value="TimeSpan" />
            <enumeration value="TimeSpan?" />
            <enumeration value="DateTime" />
            <enumeration value="DateTime?" />
            <enumeration value="XElement" />
        </restriction>
    </simpleType>

    <simpleType name="Nullness">
        <restriction base="string">
            <enumeration value="NotNull" />
            <enumeration value="CanBeNull" />
            <enumeration value="Omit" />
        </restriction>
    </simpleType>

    <simpleType name="Type">
        <union memberTypes="x:StandardType NCName" />
    </simpleType>

    <attributeGroup name="PropertiesCommonAttributes">
        <attribute name="Name" type="NCName" use="required" />
        <attribute name="Comment" type="string" use="required" />
        <attribute name="CommentEn" type="string" />
        <attribute name="ObsolescenseComment" type="string" use="optional" />
        <attribute name="ObsolescenseCommentEn" type="string" use="optional" />
    </attributeGroup>

    <complexType name="Property">
        <attributeGroup ref="x:PropertiesCommonAttributes" />
        <attribute name="Type" type="x:Type" use="required" />
        <attribute name="Nullness" type="x:Nullness" use="optional" default="Omit" />
    </complexType>

    <complexType name="Collection">
        <attributeGroup ref="x:PropertiesCommonAttributes" />
        <attribute name="ItemType" type="x:Type" use="required" />
    </complexType>

    <complexType name="Dictionary">
        <attributeGroup ref="x:PropertiesCommonAttributes" />
        <attribute name="KeyType" type="x:Type" use="required" />
        <attribute name="ValueType" type="x:Type" use="required" />
    </complexType>

    <complexType name="Include">
        <attribute name="PropertiesGroupId" type="NCName" use="required" />
    </complexType>

    <complexType name="Inherit">
        <attribute name="Model" type="NCName" use="required" />
    </complexType>

    <complexType name="PropertiesGroup">
        <choice minOccurs="1" maxOccurs="unbounded">
            <element name="Include" type="x:Include" />
            <element name="Property" type="x:Property" />
            <element name="Collection" type="x:Collection" />
            <element name="Dictionary" type="x:Dictionary" />
        </choice>
        <attribute name="Id" type="NCName" use="required" />
    </complexType>

    <complexType name="Model">
        <choice minOccurs="1" maxOccurs="unbounded">
            <element name="Inherit" type="x:Inherit" />
            <element name="Include" type="x:Include" />
            <element name="Property" type="x:Property" />
            <element name="Collection" type="x:Collection" />
            <element name="Dictionary" type="x:Dictionary" />
        </choice>
        <attribute name="Name" type="NCName" use="required" />
        <attribute name="Comment" type="string" use="required" />
        <attribute name="CommentEn" type="string" />
        <attribute name="TemplateRootModel" type="boolean" default="false" />
        <attribute name="OmitAbstract" type="boolean" default="false" />
    </complexType>

    <complexType name="EnumValue">
        <attribute name="Name" type="NCName" use="required" />
        <attribute name="Comment" type="string" use="required" />
        <attribute name="CommentEn" type="string" />
    </complexType>

    <complexType name="Enum">
        <sequence>
            <element name="Value" type="x:EnumValue" minOccurs="2" maxOccurs="unbounded" />
        </sequence>
        <attribute name="Name" type="NCName" use="required" />
        <attribute name="Comment" type="string" use="required" />
        <attribute name="CommentEn" type="string" />
    </complexType>

    <element name="Root">
        <complexType>
            <choice minOccurs="1" maxOccurs="unbounded">
                <element name="PropertiesGroup" type="x:PropertiesGroup" minOccurs="0" maxOccurs="unbounded">
                    <unique name="PropertiesGroup.UniquePropertiesGroupId">
                        <selector xpath="x:Include" />
                        <field xpath="@PropertiesGroupId" />
                    </unique>
                    <unique name="PropertiesGroup.UniquePropertyName">
                        <selector xpath="x:Property | x:Collection | x:Dictionary" />
                        <field xpath="@Name" />
                    </unique>
                </element>

                <element name="Model" type="x:Model" minOccurs="1" maxOccurs="unbounded">
                    <unique name="Model.UniquePropertiesGroupId">
                        <selector xpath="x:Include" />
                        <field xpath="@PropertiesGroupId" />
                    </unique>
                    <unique name="Model.UniquePropertyName">
                        <selector xpath="x:Property | x:Collection | x:Dictionary" />
                        <field xpath="@Name" />
                    </unique>
                </element>

                <element name="Enum" type="x:Enum" minOccurs="0" maxOccurs="unbounded">
                    <unique name="UniqueEnumValue">
                        <selector xpath="x:Value" />
                        <field xpath="@Name" />
                    </unique>
                </element>
            </choice>
        </complexType>

        <unique name="UniqueEnumName">
            <selector xpath="x:Enum" />
            <field xpath="@Name" />
        </unique>

        <key name="PropertiesGroupId">
            <selector xpath="x:PropertiesGroup" />
            <field xpath="@Id" />
        </key>

        <keyref name="PropertiesGroup.Include" refer="x:PropertiesGroupId">
            <selector xpath="x:PropertiesGroup/x:Include" />
            <field xpath="@PropertiesGroupId" />
        </keyref>

        <keyref name="Model.Include" refer="x:PropertiesGroupId">
            <selector xpath="x:Model/x:Include" />
            <field xpath="@PropertiesGroupId" />
        </keyref>

        <key name="Model.Name">
            <selector xpath="x:Model" />
            <field xpath="@Name" />
        </key>

        <keyref name="Model.Inherit" refer="x:Model.Name">
            <selector xpath="x:Model/x:Inherit" />
            <field xpath="@Model" />
        </keyref>
    </element>

</schema>

=== rengal/template.net/Resto.Front.PrintTemplates/Reports/TemplateModels/EventWrappers.xml
<?xml version="1.0" encoding="utf-8"?>
<Root
    xmlns="http://iiko.ru/XmlSchemas/TemplateModels.xsd"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://iiko.ru/XmlSchemas/TemplateModels.xsd ..\..\TemplateModels.xsd">

  <Model Name="ItemSaleEvent" Comment="Событие продажи позиции заказа" CommentEn="Order item sale event">
    <Property Name="Order" Type="Order" Nullness="CanBeNull" Comment="Заказ, которому принадлежит позиция" CommentEn="Item’s order" />
    <Property Name="Vat" Type="decimal" Comment="Ставка НДС" CommentEn="VAT rate" />
    <Property Name="VatSum" Type="decimal" Comment="Сумма НДС" CommentEn="VAT amount" />
    <Property Name="RemovalType" Type="RemovalType" Nullness="CanBeNull" Comment="Причина удаления блюда" CommentEn="Reason for deletion of item" />
    <Property Name="DeletedWithWriteoff" Type="bool?" Comment="Признак того, что блюдо было удалено из заказа со списанием: null — блюдо не было удалено, true — блюдо было удалено со списанием, false — блюдо было удалено без списания." CommentEn="An attribute implying item’s removal from an order with write-off: null - an item has not been removed, true - an item has been removed and written off, false - an item has been removed w/o write-off." />
    <Property Name="Dish" Type="Product" Nullness="NotNull" Comment="Блюдо позиции заказа" CommentEn="Dish in order item" />
    <Property Name="Amount" Type="decimal" Comment="Количество блюда" CommentEn="Item's quantity" />
    <Property Name="Sum" Type="decimal" Comment="Сумма по позиции заказа" CommentEn="Order item amount" />
    <Property Name="SumAfterDiscount" Type="decimal" Comment="Сумма по позиции заказа с учетом скидки и наценки" CommentEn="Order item amount after discounts and surcharges" />
    <Property Name="Waiter" Type="User" Nullness="CanBeNull" Comment="Официант заказа" CommentEn="Waiter handling the order" />
    <Property Name="CookingPlaceType" Type="CookingPlaceType" Nullness="CanBeNull" Comment="Тип места приготовления блюда" CommentEn="Production place type of item" />
    <Property Name="OrderId" Type="Guid" Comment="ID заказа, которому принадлежит позиция" CommentEn="Item’s order ID" />
  </Model>

  <Model Name="PayInOutEvent" Comment="Событие внесения/изъятия" CommentEn="Pay in/out event">
    <Property Name="Date" Type="DateTime" Comment="Дата" CommentEn="Date" />
    <Property Name="Account" Type="Account" Nullness="CanBeNull" Comment="Счёт" CommentEn="Account" />
    <Property Name="Comment" Type="string" Nullness="CanBeNull" Comment="Комментарий" CommentEn="Comment" />
    <Property Name="PayInOutType" Type="PayInOutType" Nullness="CanBeNull" Comment="Тип внесения/изъятия. При автоматических внесениях/изъятиях в процессе закрытия смены свойство равно null" CommentEn="Pay in/out type. In case of auto pay in/out at closing a shift, the attribute is null" />
    <Property Name="PaymentSum" Type="decimal" Comment="Сумма внесения/изъятия" CommentEn="Pay in/out amount" />
    <Property Name="Auth" Type="AuthData" Nullness="CanBeNull" Comment="Аутентификационные данные пользователя, подтвердившего внесение/изъятие" CommentEn="User authentication data who confirmed pay in/out" />
    <Property Name="User" Type="User" Comment="Залогиненный на момент события пользователь" CommentEn="User that was signed in at the time of event" />
    <Property Name="CounterAgent" Type="User" Comment="Контрагент" CommentEn="Counterparty" />
    <Property Name="TransactionType" Type="PayInOutTransactionType" Comment="Тип транзакции события внесения/изъятия" CommentEn="Pay in/out transaction type" />
    <Property Name="IsWaiterDebt" Type="bool" Comment="Признак того, что внесение/изъятие было произведено за счет официанта" CommentEn="Attribute signaling that a pay in/out has been carried out on account of waiter" />
    <Property Name="OrderId" Type="Guid?" Comment="Идентификатор заказа. Обязательное поле при оплате заказа на сотрудника." CommentEn="Order ID." />
    <Property Name="IsPayOutForCourierChange" Type="bool" Comment="Признак того, что было произведено изъятие денег, выданных курьеру на сдачу." CommentEn="Attribute signaling that a pay out has been carried out for courier change." />
  </Model>
</Root>

=== rengal/template.net/Resto.Front.PrintTemplates/Reports/TemplateModels/TransactionWrappers.xml
<?xml version="1.0" encoding="utf-8"?>
<Root
    xmlns="http://iiko.ru/XmlSchemas/TemplateModels.xsd"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://iiko.ru/XmlSchemas/TemplateModels.xsd ..\..\TemplateModels.xsd">

    <Model Name="OrderPaymentTransaction" Comment="Транзакция оплаты заказа" CommentEn="Order payment transaction">
        <Property Name="OrderId" Type="Guid" Comment="ID заказа, которому принадлежит оплата" CommentEn="Order ID an payment belongs to" />
        <Property Name="Order" Type="Order" Nullness="CanBeNull" Comment="Заказ, которому принадлежит оплата" CommentEn="Order an payment belongs to" />
        <Property Name="Cashier" Type="User" Nullness="NotNull" Comment="Кассир" CommentEn="Cashier" />
        <Property Name="Date" Type="DateTime" Comment="Дата/время транзакции" CommentEn="Transaction date/time" />
        <Property Name="Sum" Type="decimal" Comment="Сумма транзакции" CommentEn="Transaction amount" />
        <Property Name="IsFiscal" Type="bool" Comment="Фискальная ли транзакция" CommentEn="Whether the transaction is fiscal" />
        <Property Name="PaymentType" Type="PaymentType" Nullness="NotNull" Comment="Тип оплаты" CommentEn="Payment type" />
        <Property Name="DonationType" Type="DonationType" Nullness="CanBeNull" Comment="Тип чаевых" CommentEn="Type of tips" />
        <Property Name="TransactionType" Type="OrderPaymentTransactionType" Comment="Тип транзакции" CommentEn="Transaction type" />
        <Property Name="ChequeNumber" Type="int" Comment="Номер чека" CommentEn="Receipt No." />
        <Property Name="IsPurchase" Type="bool" Comment="Покупка через фронт" CommentEn="A purchase made in iikoFront" />
        <Property Name="AuthData" Type="AuthData" Nullness="CanBeNull" Comment="Кем авторизована транзакция оплаты" CommentEn="Payment authorized by" />
        <Property Name="IsWaiterDebt" Type="bool" Comment="Признак того, что транзакция оплаты заказа была произведена за счет официанта" CommentEn="Attribute signaling that a transaction has been carried out on account of waiter" />
        <Property Name="IsDeliveryOrder" Type="bool" Comment="Флаг доставочного заказа" CommentEn="Delivery order flag" />
        <Property Name="CurrencyInfo" Type="CurrencyInfo" Nullness="CanBeNull" Comment="Информация об оплате в дополнительной валюте. null, если оплата в основной валюте" CommentEn="Secondary currency information. null if the primary currency used" />
    </Model>

    <Model Name="CashPaymentTransaction" Comment="Транзакция оплаты заказа наличными" CommentEn="Cash transaction">
        <Inherit Model="OrderPaymentTransaction" />
    </Model>
    
    <Model Name="CreditPaymentTransaction" Comment="Транзакция оплаты заказа в кредит" CommentEn="On-account transaction" >
        <Inherit Model="OrderPaymentTransaction" />
        <Property Name="Counteragent" Type="User" Comment="Контрагент" CommentEn="Counterparty" />
        <Property Name="CreditCounteragentCardSlided" Type="bool" Comment="Была ли прокатана карта контрагента" CommentEn="Was the counter party's card swiped" />
    </Model>

    <Model Name="VoucherPaymentTransaction" Comment="Транзакция оплаты заказа ваучерами" CommentEn="Coupon transaction" >
        <Inherit Model="OrderPaymentTransaction" />
        <Property Name="Nominal" Type="decimal" Comment="Номинал" CommentEn="Nominal value" />
        <Property Name="VouchersNum" Type="int" Comment="Количество использованных ваучеров" CommentEn="Number of coupons used" />
    </Model>
    
    <Model Name="OrderPrepayTransaction" Comment="Транзакция предоплаты заказа" CommentEn="Prepayment transaction" >
        <Inherit Model="OrderPaymentTransaction" />
    </Model>

    <Model Name="OrderPrepayClosedTransaction" Comment="Транзакция закрытия предоплаты заказа" CommentEn="Prepayment closing transaction" >
        <Inherit Model="OrderPaymentTransaction" />
    </Model>
    
    <Enum Name="OrderPaymentTransactionType" Comment="Тип транзакции оплаты заказа" CommentEn="Transaction type">
        <Value Name="Cash" Comment="Продажа за наличные" CommentEn="Cash sales" />
        <Value Name="Card" Comment="Выручка по картам" CommentEn="Non-cash revenue" />
        <Value Name="Credit" Comment="Выручка в кредит" CommentEn="On-account revenue" />
        <Value Name="OnTheHouse" Comment="Оплата заказа за счет заведения" CommentEn="On-the-house" />
        <Value Name="PrepayClosed" Comment="Продажа с предоплатой" CommentEn="Prepaid sales" />
        <Value Name="Prepay" Comment="Внесение предоплаты" CommentEn="Making prepayment" />
        <Value Name="PrepayReturn" Comment="Возврат предоплаты" CommentEn="Prepayment refund" />
        <Value Name="PrepayClosedReturn" Comment="Возврат продажи с предоплатой" CommentEn="Prepaid sale refund" />
        <Value Name="RevenueReturn" Comment="Возврат денег покупателю" CommentEn="Revenue money to customer" />
        <Value Name="Donations" Comment="Чаевые" CommentEn="Donations" />
    </Enum>
    
    <Model Name="PayInOutFiscalTransaction" Comment="Транзакция фискального внесения/изъятия" CommentEn="Fiscal pay in/out transaction">
        <Property Name="Sum" Type="decimal" Comment="Сумма" CommentEn="Total" />
        <Property Name="IsPayIn" Type="bool" Comment="Флаг внесения/изъятия" CommentEn="Pay in/out flag" />
        <Property Name="TransactionType" Type="PayInOutTransactionType" Comment="Тип транзакции внесения/изъятия" CommentEn="Pay in/out transaction type" />
    </Model>
</Root>
