=== rengal/template.net/Resto.Front.PrintTemplates/Cheques/Xslt/TemplateModels/Documents.xsd
<?xml version="1.0" encoding="utf-8"?>
<schema targetNamespace="http://iiko.ru/XmlSchemas/Documents.xsd"
        xmlns:doc="http://iiko.ru/XmlSchemas/Documents.xsd"
        xmlns="http://www.w3.org/2001/XMLSchema"
        elementFormDefault="qualified">

  <!-- SIMPLE TYPES -->

  <simpleType name="DataType">
    <union memberTypes="NCName doc:DataTypeEnum" />
  </simpleType>
  <simpleType name="DataTypeEnum">
    <restriction base="string">
      <enumeration value="bool" />
      <enumeration value="string" />
      <enumeration value="decimal" />
      <enumeration value="int" />
      <enumeration value="DateTime" />
      <enumeration value="TimeSpan" />
    </restriction>
  </simpleType>

  <!-- DOCUMENTS -->

  <complexType name="Property">
    <attribute name="Name" type="NCName" use="required" />
    <attribute name="ItemName" type="NCName" />
    <attribute name="Type" type="doc:DataType" use="required" />
    <attribute name="Collection" type="boolean" default="false" />
    <attribute name="Comment" type="string" use="optional" />
  </complexType>

  <complexType name="Resource">
    <attribute name="Name" type="NCName" use="required" />
    <attribute name="Type" type="doc:DataType" use="required" />
  </complexType>

  <complexType name="Type">
    <sequence>
      <element name="Property" type="doc:Property" maxOccurs="unbounded" />
      <element name="Resource" type="doc:Resource" maxOccurs="unbounded" minOccurs="0" />
    </sequence>
    <attribute name="Name" type="NCName" use="required" />
    <attribute name="ItemName" type="NCName" />
    <attribute name="Root" type="boolean" default="false" />
    <attribute name="Comment" type="string" use="optional" />
  </complexType>

  <element name="Type" type="doc:Type">
    <key name="Document.Type.Property.Name">
      <selector xpath="doc:Property" />
      <field xpath="@Name" />
    </key>
  </element>

  <complexType name="Document">
    <sequence>
      <element ref="doc:Type" maxOccurs="unbounded" />
    </sequence>
    <attribute name="Name" type="NCName" use="required" />
    <attribute name="Comment" type="string" use="optional" />
  </complexType>

  <!-- ROOT -->

  <element name="Root">
    <complexType>
      <choice maxOccurs="unbounded">
        <element name="Document" type="doc:Document" />
      </choice>
    </complexType>

    <!-- Document keys -->
    <key name="Document.Name">
      <selector xpath="doc:Document" />
      <field xpath="@Name" />
    </key>
    <key name="Document.Type.Name">
      <selector xpath="doc:Document/doc:Type" />
      <field xpath="@Name" />
    </key>
  </element>

</schema>

=== rengal/template.net/Resto.Front.PrintTemplates/Cheques/Xslt/TemplateModels/Documents.xml
<?xml version="1.0" encoding="utf-8"?>
<Root xmlns="http://iiko.ru/XmlSchemas/Documents.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://iiko.ru/XmlSchemas/Documents.xsd Documents.xsd">

  <!-- DOCUMENTS -->

  <!-- Cheques: Common -->

  <Document Name="ChequesCommon">
    <Type Name="ChequeSettings">
      <Property Name="ChequeHeader" Type="string" />
      <Property Name="ChequeFooter" Type="string" />
      <Property Name="UserName" Type="string" />
      <Property Name="GroupName" Type="string" />
      <Property Name="CurrencyName" Type="string" />
      <Property Name="ShortCurrencyName" Type="string" />
      <Property Name="Now" Type="DateTime" />
      <Property Name="EnterpriseName" Type="string" />
      <Resource Name="Resources" Type="ChequeResources" />
    </Type>

    <!-- Дополнения к документам, вычисляются асинхронно в фоне (в т.ч. плагинами) -->
    <Type Name="ChequeExtensions">
      <Property Name="BeforeHeader" Type="XElement" Collection="true" />
      <Property Name="AfterHeader" Type="XElement" Collection="true" />
      <Property Name="BeforeFooter" Type="XElement" Collection="true" />
      <Property Name="AfterFooter" Type="XElement" Collection="true" />
    </Type>
  </Document>

  <!-- Price tickets (этикетки) -->
  <Document Name="PriceTicket">
    <Type Name="PriceTicket" Root="true" Comment="Этикетка">
      <Property Name="Settings" Type="ChequeSettings" />
      <Property Name="ProductName" Type="string" Comment="Наименование номерклатуры" />
      <Property Name="Amount" Type="decimal" Comment="Количество" />
      <Property Name="Price" Type="decimal" Comment="Цена" />
      <Property Name="Cost" Type="decimal" Comment="Стоимость" />
      <Property Name="UnitName" Type="string" Comment="Единица измерения" />
      <Property Name="Composition" Type="string" Comment="Состав" />
      <Property Name="FoodValue" Type="FoodValue" Comment="Пищевая ценность" />
      <Property Name="IsExpirationPeriodSet" Type="bool" Comment="Задан ли срок хранения" />
      <Property Name="ExpirationPeriod" Type="TimeSpan" Comment="Срок хранения" />
      <Property Name="BestBeforeTime" Type="DateTime" Comment="Годен до" />
      <Property Name="MakeTime" Type="DateTime" Comment="Время изготовления" />
      <Property Name="BarcodeString" Type="string" Comment="Штрихкод" />
    </Type>

    <Type Name="FoodValue" Comment="Пищевая ценность">
      <Property Name="IsEmpty" Type="bool" Comment="Заполнено ли" />
      <Property Name="Fat" Type="decimal" Comment="Жиры" />
      <Property Name="Protein" Type="decimal" Comment="Белки" />
      <Property Name="Carbohydrate" Type="decimal" Comment="Углеводы" />
      <Property Name="Caloricity" Type="decimal" Comment="Калорийность" />
    </Type>
  </Document>

  <!-- Cheques: Service -->

  <!-- Delivery stickers (стикеры) -->
  <Document Name="DeliverySticker">
    <Type Name="DeliverySticker" Root="true" Comment="Стикер">
      <Property Name="Settings" Type="ChequeSettings" Comment="Настройки чеков" />
      <!-- Delivery info -->
      <Property Name="DeliveryNumber" Type="int" Comment="Номер доставки" />
      <Property Name="DeliverTime" Type="DateTime" Comment="Время доставки" />
      <!-- Position info -->
      <Property Name="OrderItem" Type="DeliveryStickerOrderItemInfo" Comment="Блюдо" />
    </Type>

    <Type Name="DeliveryStickerOrderEntryInfo">
      <Property Name="Name" Type="string" Comment="Наименование номерклатуры" />
      <Property Name="Amount" Type="decimal" Comment="Количество" />
    </Type>
    <Type Name="DeliveryStickerOrderItemInfo">
      <Property Name="Name" Type="string" Comment="Наименование номенклатуры" />
      <Property Name="GuestName" Type="string" Comment="Имя гостя" />
      <Property Name="Amount" Type="decimal" Comment="Количество" />
      <Property Name="CategoryName" Type="string" Comment="Категория" />
      <Property Name="UseBalanceForSell" Type="bool" Comment="Весовое ли блюдо" />
      <Property Name="Price" Type="decimal" Comment="Цена" />
      <Property Name="Composition" Type="string" Comment="Состав" />
      <Property Name="FoodValue" Type="FoodValue" Comment="Пищевая ценность" />
      <Property Name="IsExpirationPeriodSet" Type="bool" Comment="Задан ли срок хранения" />
      <Property Name="ExpirationPeriodHours" Type="string" Comment="Срок хранения в часах" />
      <Property Name="Modifiers" Type="DeliveryStickerOrderEntryInfo" ItemName="Modifier" Collection="true" Comment="Модификаторы" />
      <Property Name="PrintTime" Type="DateTime" Comment="Время сервисной печати" />
    </Type>
  </Document>

  <Document Name="DeliveryBillCheque">
    <Type Name="DeliveryBill" Root="true">
      <Property Name="Settings" Type="ChequeSettings" />
      <Property Name="DeliveryInfo" Type="DeliveryInfo" />
      <Property Name="DeliveryOrderInfo" Type="DeliveryOrderInfo" />
      <Property Name="BillFooter" Type="BillFooter" />
    </Type>

    <Type Name="DeliveryInfo">
      <Property Name="DeliveryNumber" Type="int" />
      <Property Name="RestourantLegalName" Type="string" />
      <Property Name="TaxId" Type="string" />
      <Property Name="CustomerNameAndPatronymic" Type="string" />
      <Property Name="CustomerSurname" Type="string" />
      <Property Name="PhoneNumber" Type="string" />
      <Property Name="Address" Type="string" />
      <Property Name="Region" Type="string" />
      <Property Name="AdressComment" Type="string" />
      <Property Name="Comments" Type="string" />
      <Property Name="DiscountCardNumber" Type="string" />
      <Property Name="Manager" Type="string" />
      <Property Name="Courier" Type="string" />
      <Property Name="DeliveryOperator" Type="string" />
      <Property Name="DeliveryReceiveTime" Type="DateTime" />
      <Property Name="DeliveryBillPrintTime" Type="DateTime" />
      <Property Name="DeliverTime" Type="DateTime" />
      <Property Name="IsPayed" Type="bool" />
      <Property Name="IsSelfService" Type="bool" />
      <Property Name="SplitBetweenPersons" Type="bool" />
      <Property Name="PersonsCount" Type="int" />
    </Type>
    <Type Name="DeliveryOrderInfo">
      <Property Name="TotalSumsInfo" Type="TotalSumsInfo" />
      <Property Name="EntriesByGuests" Type="DeliveryGuest" ItemName="DeliveryGuest" Collection="true" Comment="Гости" />
      <Property Name="Discounts" Type="DiscountInfo" ItemName="Discount" Collection="true" />
      <Property Name="Prepays" Type="PaymentInfo" ItemName="Prepay" Collection="true" />
      <Property Name="Payments" Type="PaymentInfo" ItemName="Payment" Collection="true" />
      <Property Name="Vats" Type="VatInfo" ItemName="Vat" Collection="true" />
    </Type>
    <Type Name="DeliveryOrderEntryInfo" >
      <Property Name="IsModifier" Type="bool" />
      <Property Name="IsPrechequePrintable" Type="bool" />
      <Property Name="Name" Type="string" />
      <Property Name="Amount" Type="decimal" />
      <Property Name="Price" Type="decimal" />
      <Property Name="Sum" Type="decimal" />
      <Property Name="MeasuringUnitName" Type="string" />
      <Property Name="Discounts" Type="DiscountInfo" ItemName="Discount" Collection="true" />
    </Type>
    <Type Name="DeliveryGuest" Comment="Гость">
      <Property Name="Name" Type="string" Comment="Имя" />
      <Property Name="Sum" Type="decimal" Comment="Итого по гостю с учётом всех скидок/надбавок" />
      <Property Name="DeliveryItems" Type="DeliveryOrderEntryInfo" ItemName="DeliveryOrderEntryInfo" Collection="true" Comment="Заказанные блюда" />
    </Type>
    <Type Name="TotalSumsInfo">
      <Property Name="SubTotal" Type="decimal" />
      <Property Name="ResultSum" Type="decimal" />
      <Property Name="ChangeSum" Type="decimal" />
      <Property Name="VatSum" Type="decimal" />
      <Property Name="AllSumsCurrencyUnitLabel" Type="string" />
    </Type>
    <Type Name="DiscountInfo">
      <Property Name="Name" Type="string"/>
      <Property Name="Percent"  Type="decimal" />
      <Property Name="Sum" Type="decimal" />
      <Property Name="CardNumber" Type="string" />
    </Type>
    <Type Name="PaymentInfo">
      <Property Name="Name" Type="string" />
      <Property Name="Sum" Type="decimal" />
      <Property Name="IsCash" Type="bool" />
      <Property Name="IsCard" Type="bool" />
      <Property Name="CounteragentName" Type="string" />
      <Property Name="CounteragentCardNumber" Type="string" />
    </Type>
    <Type Name="VatInfo" Comment="налог, не включенный в стоимость блюда">
      <Property Name="VatPercent" Type="decimal" Comment="Процент налога" />
      <Property Name="VatSum" Type="decimal" Comment="Процент сумма" />
    </Type>
    <Type Name="BillFooter">
      <Property Name="Value" Type="string" />
    </Type>
  </Document>

  <Document Name="ServiceChequesCommon">
    <Type Name="KitchenChequeInfo" Comment="Информация о кухонном чеке">
      <Property Name="Order" Type="OrderInfo" Comment="Сведения о заказе" />
      <Property Name="PrinterCounter" Type="int" Comment="Счётчик печати" />
      <Property Name="HasCourses" Type="bool" Comment="Флаг использования курсов" />
    </Type>

    <Type Name="OrderInfo" Comment="Сведения о заказе">
      <Property Name="Number" Type="int" Comment="Номер заказа" />
      <Property Name="TableNumber" Type="int" Comment="Номер стола" />
      <Property Name="SectionName" Type="string" Comment="Название отделения" />
      <Property Name="GuestsCount" Type="int" Comment="Количество гостей" />
      <Property Name="WaiterName" Type="string" Comment="Имя официанта" />
      <Property Name="OrderOpenTime" Type="DateTime" Comment="Время открытия заказа" />
    </Type>

    <Type Name="KitchenChequeItem" ItemName="ChequeItem" Comment="Элемент сервисного чека">
      <Property Name="Course" Type="int" Comment="Курс блюд" />
      <Property Name="IsWholeMix" Type="bool" Comment="Объединяет ли элемент все смиксованные блюда" />
