=== rengal/template.net/Resto.Framework/Src/Common/Currency/Currencies.xsd
<?xml version="1.0" encoding="utf-8"?>
<schema targetNamespace="http://iiko.ru/XmlSchemas/Currencies.xsd" xmlns="http://www.w3.org/2001/XMLSchema" xmlns:a="http://iiko.ru/XmlSchemas/Currencies.xsd" elementFormDefault="qualified">

  <!-- Валюта -->
  <complexType name="Currency">

    <attribute name="Comment" type="string" use="required">
      <annotation>
        <documentation>
          Документирующий комментарий к обёртке (можно добавить как атрибут или как элемент).
        </documentation>
      </annotation>
    </attribute>

    <attribute name="Name" type="string" use="required">
      <annotation>
        <documentation>
          Имя валюты.
        </documentation>
      </annotation>
    </attribute>

    <attribute name="IsoName" type="string" use="required">
      <annotation>
        <documentation>
          ISO Наименование валюты.
        </documentation>
      </annotation>
    </attribute>

    <attribute name="ResName" type="string" use="optional">
      <annotation>
        <documentation>
          Наименование валюты в ресурсах. Если не указано - считается, что совпадает с Name.
        </documentation>
      </annotation>
    </attribute>

    <attribute name="ResKopName" type="string" use="optional">
      <annotation>
        <documentation>
          Наименование долей валюты в ресурсах. Если не указано - считается, что совпадает с ResName.
        </documentation>
      </annotation>
    </attribute>

    <attribute name="Male" type="boolean" use="required">
      <annotation>
        <documentation>
          Мужской ли род.
        </documentation>
      </annotation>
    </attribute>

    <attribute name="FracPart" type="int" use="required">
      <annotation>
        <documentation>
          Длина дробной части (количество значимых цифр после запятой)
        </documentation>
      </annotation>
    </attribute>

    <attribute name="MaxPayInOut" type="string" use="required">
      <annotation>
        <documentation>
          Максимальная сумма внесений и изъятий
        </documentation>
      </annotation>
    </attribute>
    
    <attribute name="Recalc" type="boolean" use="optional" default="true">
      <annotation>
        <documentation>
          Флаг, указывает передавать ли на ФР стоимость одной единицы и количество
          или подсчитывать итоговую сумму в соотвествии с настройками валюты и в качестве количева передавать единиц.
        </documentation>
      </annotation>
    </attribute>    
  </complexType>

  <!-- root -->
  <element name="CurrenciesList">
    <annotation>
      <documentation>
        Список валют.
      </documentation>
    </annotation>
    <complexType>
      <choice minOccurs="0" maxOccurs="unbounded">
        <element name="Currency" type="a:Currency">
          <annotation>
            <documentation>
              Валюта со списком свойств.
            </documentation>
          </annotation>
        </element>
      </choice>
    </complexType>

    <key name="Currency.Name">
      <selector xpath="Currency" />
      <field xpath="@Name" />
    </key>
  </element>
</schema>

=== rengal/template.net/Resto.Framework/Src/Common/Currency/Currencies.xml
<?xml version="1.0" encoding="utf-8"?>
<CurrenciesList xmlns="http://iiko.ru/XmlSchemas/Currencies.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://iiko.ru/XmlSchemas/Currencies.xsd Currencies.xsd">

<!---  Для округления денежных значений до разрядов в целой части используйте отрицательные значения параметра FracPart (fractionalPartLength)
       Например, при fractionalPartLength равном -1, денежные величины будут округляться до десятков рублей/долларов/etc.

       Необходимо будет добавить также соответствующие ресурсные файлы. Описание см. в RMS-23845 -->

  <Currency Name="Rus" ResName="Rub" IsoName="RUB" Comment="Российский рубль" Male="true" FracPart="2" MaxPayInOut="99999999.99m" />
  <Currency Name="Armenia" ResName="Amd" IsoName="AMD" Comment="Армянский драм" Male="true" FracPart="0" MaxPayInOut="999999999m" />
  <Currency Name="Euro" ResName="Eur" IsoName="EUR" Comment="Евро" Male="true" FracPart="2" MaxPayInOut="99999999.99m" />
  <Currency Name="Belarus" ResName="Rub" IsoName="BYR" Comment="Белорусский рубль" Male="true" FracPart="-2" MaxPayInOut="99999999m" Recalc="false"/>
  <Currency Name="BelarusNew" ResName="Rub" IsoName="BYN" Comment="Белорусский рубль после деноминации" Male="true" FracPart="2" MaxPayInOut="99999999.99m" />
  <Currency Name="USA" ResName="Usd" IsoName="USD" Comment="Американский доллар" Male="true" FracPart="2" MaxPayInOut="99999999.99m" />
  <Currency Name="Uzbekistan" ResName="Uzs" IsoName="UZS" Comment="Узбекский сум" Male="true" FracPart="0" MaxPayInOut="99999999m" />
  <Currency Name="Moldova" ResName="Mdl" IsoName="MDL" Comment="Молдавский лей" Male="true" FracPart="2" MaxPayInOut="99999999.99m" />
  <Currency Name="Ukrainian" ResName="Uah" ResKopName="Rub" IsoName="UAH" Comment="Украинская гривна" Male="false" FracPart="2" MaxPayInOut="99999999.99m" />
  <Currency Name="Chinese" ResName="Cny" IsoName="CNY" Comment="Китайский юань" Male="true" FracPart="1" MaxPayInOut="99999999.9m" />

  <Currency Name="Bif" ResName="Rwf" IsoName="BIF" Comment="Бурундийский франк" Male="true" FracPart="0" MaxPayInOut="99999999m" />
  <Currency Name="Clp" ResName="Php" IsoName="CLP" Comment="Чилийское песо" Male="true" FracPart="0" MaxPayInOut="99999999m" />
  <Currency Name="Kmf" ResName="Rwf" IsoName="KMF" Comment="Франк Комор" Male="true" FracPart="0" MaxPayInOut="99999999m" />
  <Currency Name="Djf" ResName="Rwf" IsoName="DJF" Comment="Франк Джибути" Male="true" FracPart="0" MaxPayInOut="99999999m" />
  <Currency Name="Gnf" ResName="Rwf" IsoName="GNF" Comment="Гвинейский франк" Male="true" FracPart="0" MaxPayInOut="99999999m" />
  <Currency Name="Jpy" IsoName="JPY" Comment="Иена" Male="false" FracPart="0" MaxPayInOut="99999999m" />
  <Currency Name="Krw" ResName="Kpw" IsoName="KRW" Comment="Вона" Male="true" FracPart="0" MaxPayInOut="99999999m" />
  <Currency Name="Vuv" IsoName="VUV" Comment="Вату" Male="true" FracPart="0" MaxPayInOut="99999999m" />
  <Currency Name="Pyg" ResKopName="Aoa" IsoName="PYG" Comment="Гуарани" Male="true" FracPart="0" MaxPayInOut="99999999m" />
  <Currency Name="Rwf" IsoName="RWF" Comment="Франк Руанды" Male="true" FracPart="0" MaxPayInOut="99999999m" />
  <Currency Name="Xaf" ResName="Rwf" IsoName="XAF" Comment="Франк КФА ВЕАС" Male="true" FracPart="0" MaxPayInOut="99999999m" />
  <Currency Name="Xof" ResName="Rwf" IsoName="XOF" Comment="Франк КФА ВСЕАО" Male="true" FracPart="0" MaxPayInOut="99999999m" />
  <Currency Name="Xpf" ResName="Rwf" IsoName="XPF" Comment="Франк КФП" Male="true" FracPart="0" MaxPayInOut="99999999m" />
  <Currency Name="Mga" IsoName="MGA" Comment="Малагасийский ариари" Male="true" FracPart="0" MaxPayInOut="99999999m" />  
  <Currency Name="All" IsoName="ALL" Comment="Лек" Male="true" FracPart="2" MaxPayInOut="99999999.99m" />
  <Currency Name="Dzd" ResName="Bhd" ResKopName="Rwf" IsoName="DZD" Comment="Алжирский динар" Male="true" FracPart="2" MaxPayInOut="99999999.99m" />
  <Currency Name="Ars" ResName="Php" IsoName="ARS" Comment="Аргентинское песо" Male="true" FracPart="2" MaxPayInOut="99999999.99m" />
  <Currency Name="Aud" ResName="Usd" IsoName="AUD" Comment="Австралийский доллар" Male="true" FracPart="2" MaxPayInOut="99999999.99m" />
  <Currency Name="Bsd" ResName="Usd" IsoName="BSD" Comment="Багамский доллар" Male="true" FracPart="2" MaxPayInOut="99999999.99m" />
  <Currency Name="Bdt" ResKopName="Inr" IsoName="BDT" Comment="Така" Male="false" FracPart="2" MaxPayInOut="99999999.99m" />
  <Currency Name="Bbd" ResName="Usd" IsoName="BBD" Comment="Барбадосский доллар" Male="true" FracPart="2" MaxPayInOut="99999999.99m" />
  <Currency Name="Bmd" ResName="Usd" IsoName="BMD" Comment="Бермудский доллар" Male="true" FracPart="2" MaxPayInOut="99999999.99m" />
  <Currency Name="Btn" IsoName="BTN" Comment="Нгултрум" Male="true" FracPart="2" MaxPayInOut="99999999.99m" />
  <Currency Name="Bob" ResKopName="Php" IsoName="BOB" Comment="Боливиано" Male="true" FracPart="2" MaxPayInOut="99999999.99m" />
  <Currency Name="Bwp" IsoName="BWP" Comment="Пула" Male="false" FracPart="2" MaxPayInOut="99999999.99m" />
  <Currency Name="Bzd" ResName="Usd" IsoName="BZD" Comment="Белизский доллар" Male="true" FracPart="2" MaxPayInOut="99999999.99m" />
  <Currency Name="Sbd" ResName="Usd" IsoName="SBD" Comment="Доллар Соломоновых Островов" Male="true" FracPart="2" MaxPayInOut="99999999.99m" />
  <Currency Name="Bnd" ResName="Usd" ResKopName="Idr" IsoName="BND" Comment="Брунейский доллар" Male="true" FracPart="2" MaxPayInOut="99999999.99m" />
  <Currency Name="Mmk" IsoName="MMK" Comment="Кьят" Male="true" FracPart="2" MaxPayInOut="99999999.99m" />
  <Currency Name="Khr" ResKopName="Idr" IsoName="KHR" Comment="Риель" Male="true" FracPart="2" MaxPayInOut="99999999.99m" />
  <Currency Name="Cad" ResName="Usd" IsoName="CAD" Comment="Канадский доллар" Male="true" FracPart="2" MaxPayInOut="99999999.99m" />
  <Currency Name="Cve" ResKopName="Php" IsoName="CVE" Comment="Эскудо Кабо-Верде" Male="true" FracPart="2" MaxPayInOut="99999999.99m" />
  <Currency Name="Kyd" ResName="Usd" IsoName="KYD" Comment="Доллар Островов Кайман" Male="true" FracPart="2" MaxPayInOut="99999999.99m" />
  <Currency Name="Lkr" ResName="Inr" ResKopName="Usd" IsoName="LKR" Comment="Шри-Ланкийская рупия" Male="false" FracPart="2" MaxPayInOut="99999999.99m" />  
  <Currency Name="Cop" ResName="Php" IsoName="COP" Comment="Колумбийское песо" Male="true" FracPart="2" MaxPayInOut="99999999.99m" />
  <Currency Name="Crc" ResKopName="Aoa" IsoName="CRC" Comment="Костариканский колон" Male="true" FracPart="2" MaxPayInOut="99999999.99m" />
  <Currency Name="Hrk" IsoName="HRK" Comment="Хорватская куна" Male="false" FracPart="2" MaxPayInOut="99999999.99m" />
  <Currency Name="Cup" ResName="Php" IsoName="CUP" Comment="Кубинское песо" Male="true" FracPart="2" MaxPayInOut="99999999.99m" />
  <Currency Name="Czk" ResName="Dkk" ResKopName="Czk" IsoName="CZK" Comment="Чешская крона" Male="false" FracPart="2" MaxPayInOut="99999999.99m" />
  <Currency Name="Dkk" IsoName="DKK" Comment="Датская крона" Male="false" FracPart="2" MaxPayInOut="99999999.99m" />
  <Currency Name="Dop" ResName="Php" IsoName="DOP" Comment="Доминиканское песо" Male="true" FracPart="2" MaxPayInOut="99999999.99m" />
  <Currency Name="Etb" ResKopName="Usd" IsoName="ETB" Comment="Эфиопский быр" Male="true" FracPart="2" MaxPayInOut="99999999.99m" />
  <Currency Name="Ern" ResKopName="Usd" IsoName="ERN" Comment="Накфа" Male="false" FracPart="2" MaxPayInOut="99999999.99m" />
  <Currency Name="Fkp" ResName="Egp" ResKopName="Sgd" IsoName="FKP" Comment="Фунт Фолклендских островов" Male="true" FracPart="2" MaxPayInOut="99999999.99m" />
  <Currency Name="Fjd" ResName="Usd" IsoName="FJD" Comment="Доллар Фиджи" Male="true" FracPart="2" MaxPayInOut="99999999.99m" />
  <Currency Name="Gmd" IsoName="GMD" Comment="Даласи" Male="true" FracPart="2" MaxPayInOut="99999999.99m" />
  <Currency Name="Gip" ResName="Egp" ResKopName="Sgd" IsoName="GIP" Comment="Гибралтарский фунт" Male="true" FracPart="2" MaxPayInOut="99999999.99m" />
  <Currency Name="Gtq" ResKopName="Php" IsoName="GTQ" Comment="Кетсаль" Male="true" FracPart="2" MaxPayInOut="99999999.99m" />
  <Currency Name="Gyd" ResName="Usd" IsoName="GYD" Comment="Гайанский доллар" Male="true" FracPart="2" MaxPayInOut="99999999.99m" />
  <Currency Name="Htg" ResKopName="Rwf" IsoName="HTG" Comment="Гурд" Male="true" FracPart="2" MaxPayInOut="99999999.99m" />
  <Currency Name="Hnl" ResKopName="Php" IsoName="HNL" Comment="Лемпира" Male="false" FracPart="2" MaxPayInOut="99999999.99m" />
  <Currency Name="Hkd" ResName="Usd" ResKopName="Vnd" IsoName="HKD" Comment="Гонконгский доллар" Male="true" FracPart="2" MaxPayInOut="99999999.99m" />
  <Currency Name="Huf" IsoName="HUF" Comment="Форинт" Male="true" FracPart="2" MaxPayInOut="99999999.99m" />
  <Currency Name="Isk" ResName="Dkk" IsoName="ISK" Comment="Исландская крона" Male="false" FracPart="2" MaxPayInOut="99999999.99m" />
  <Currency Name="Inr" IsoName="INR" Comment="Индийская рупия" Male="false" FracPart="2" MaxPayInOut="99999999.99m" />
  <Currency Name="Idr" ResName="Inr" ResKopName="Idr" IsoName="IDR" Comment="Рупия" Male="false" FracPart="2" MaxPayInOut="99999999.99m" />
  <Currency Name="Irr" IsoName="IRR" Comment="Иранский риал" Male="true" FracPart="2" MaxPayInOut="99999999.99m" />
  <Currency Name="Ils" IsoName="ILS" Comment="Новый израильский шекель" Male="true" FracPart="2" MaxPayInOut="99999999.99m" />
  <Currency Name="Jmd" ResName="Usd" IsoName="JMD" Comment="Ямайский доллар" Male="true" FracPart="2" MaxPayInOut="99999999.99m" />
  <Currency Name="Kzt" IsoName="KZT" Comment="Тенге" Male="true" FracPart="2" MaxPayInOut="99999999.99m" />
  <Currency Name="Kes" ResName="Sos" ResKopName="Usd" IsoName="KES" Comment="Кенийский шиллинг" Male="true" FracPart="2" MaxPayInOut="99999999.99m" />
  <Currency Name="Kpw" IsoName="KPW" Comment="Северокорейская вона" Male="false" FracPart="2" MaxPayInOut="99999999.99m" />
